language: java
#sudo: false #faster builds

jdk:
  - oraclejdk8
    
cache:
  directories:
    - '$HOME/.m2/repository'

before_install:
  - chmod +x mvnw
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

before_script:
  - _JAVA_OPTIONS=
  
script:
 - "./mvnw clean test"

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
  - ls -la build/
  - ls -la build/reports/
  - ls -la build/reports/jacoco/
  - ls -la build/reports/jacoco/test/