language: java
sudo: false # faster builds
jdk:
  - oraclejdk8
    
cache:
  directories:
    - '$HOME/.m2/repository'

before_install:
  - chmod +x mvnw
  
before_script:
  - _JAVA_OPTIONS=
  
script:
 - "./mvnw clean install cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
